apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: replaceme_base64_encoded
  AWS_SECRET_ACCESS_KEY: replaceme_base64_encoded
#  VAULT_AWS_REGION: replaceme_base64_encoded
#  VAULT_AWSKMS_SEAL_KEY_ID: replaceme_base64_encoded
kind: Secret
metadata:
  creationTimestamp: null
  name: kms-creds
  namespace: vault
