## create a selfsigned-issuer at --namespace="vault"
# kubectl apply -f https://gist.githubusercontent.com/t83714/51440e2ed212991655959f45d8d037cc/raw/7b16949f95e2dd61e522e247749d77bc697fd63c/selfsigned-issuer.yaml -n vault

## key size: 2048
## PKI needs to renew once per year (8760 hrs = 365 days)
## set to autorotate 15 minutes before expiry date

## example to build a "vault" namespace
## add the parameters to build the certificate
## vault-ha-tls   should contains all 3  vault.tls, vault.key, vault.ca in base64 encoded format

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-ha-tls
  namespace: vault
spec:
  secretName: vault-ha-tls
  subject:
    organizations:
      - system:nodes
  commonName: system:node:*.vault.svc.cluster.local
  duration: 8760h # 365d
  renewBefore: 360h # 15d
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  dnsNames:
    - "*.vault-internal"
    - "*.vault-internal.vault.svc.cluster.local"
    - "*.vault"
  ipAddresses:
    - 127.0.0.1
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer